import { promises as fs } from "fs";
import path from "path";
import { randomUUID } from "crypto";
import type { ImageStorage, StoredImage, UploadInput } from "./index";

const EXT_BY_TYPE: Record<string, string> = {
  "image/avif": ".avif",
  "image/gif": ".gif",
  "image/heic": ".heic",
  "image/jpeg": ".jpg",
  "image/png": ".png",
  "image/svg+xml": ".svg",
  "image/webp": ".webp",
};

const TYPE_BY_EXT: Record<string, string> = {
  ".avif": "image/avif",
  ".gif": "image/gif",
  ".heic": "image/heic",
  ".jpeg": "image/jpeg",
  ".jpg": "image/jpeg",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".webp": "image/webp",
};

// Keys are always generated by upload(), so anything outside this shape is a
// forged request — rejecting it also blocks path traversal out of rootDir.
const KEY_PATTERN = /^[A-Za-z0-9-]+(\.[A-Za-z0-9]+)?$/;

/**
 * ImageStorage backed by a directory on the local filesystem. The directory
 * is created on first upload if it doesn't exist.
 */
export class LocalImageStorage implements ImageStorage {
  constructor(private readonly rootDir: string) {}

  private filePath(key: string): string | null {
    if (!KEY_PATTERN.test(key)) return null;
    return path.join(this.rootDir, key);
  }

  async upload(input: UploadInput): Promise<string> {
    const ext =
      (input.contentType && EXT_BY_TYPE[input.contentType]) ||
      (input.filename ? path.extname(input.filename).toLowerCase() : "");
    const key = `${randomUUID()}${ext}`;
    await fs.mkdir(this.rootDir, { recursive: true });
    await fs.writeFile(this.filePath(key)!, input.data);
    return key;
  }

  async download(key: string): Promise<StoredImage | null> {
    const filePath = this.filePath(key);
    if (!filePath) return null;
    try {
      const data = await fs.readFile(filePath);
      return {
        data: new Uint8Array(data),
        contentType:
          TYPE_BY_EXT[path.extname(key).toLowerCase()] ?? "application/octet-stream",
      };
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
      throw err;
    }
  }

  async delete(key: string): Promise<void> {
    const filePath = this.filePath(key);
    if (!filePath) return;
    await fs.rm(filePath, { force: true });
  }
}
